# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: Pull Request Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commitlint:
    uses: diggsweden/.github/.github/workflows/commit-lint.yml@main
  dependencyreviewlint:
    uses: diggsweden/.github/.github/workflows/dependency-review.yml@main
  licenselint:
    uses: diggsweden/.github/.github/workflows/license-lint.yml@main
  misclint:
    permissions:
      contents: read
      security-events: write
    uses: diggsweden/.github/.github/workflows/megalint.yml@main
  test:
    permissions:
      contents: read
      packages: read
    if: always()
    needs: [commitlint,misclint,licenselint,dependencyreviewlint]
    uses: ./.github/workflows/test.yml
